# Generated by Django 4.2.7 on 2023-11-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
